config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='')),
    path('projects/', include('project.urls', namespace='')),
]

# Запрещаем кэширование на стороне клиента, если сайт функционирует
# в отладочном режиме
# if settings.DEBUG:
#     urlpatterns.append(path('static/<path:path>', never_cache(serve)))

project/urls.py
from django.urls import path

from project.views import (
    add_keywords_group,
    get_cities_to_choose,
    AddKeywordsView,
    AddProjectView,
    AddSearchSystemView,
    ChangeProjectView,
    DetailKeywordsGroupView,
    DetailProjectView,
    DetailSearchSystemsView,
    DeleteProjectView,
    ProjectListView,
    PositionCheckView,
)

app_name = 'project'
urlpatterns = [
    path('all/check/', PositionCheckView.as_view(), name='check_all_positions'),
    path('keywords/add/<int:project_id>/', AddKeywordsView.as_view(), name='keywords_create'),
    path('keywords_group/detail/<int:pk>/', DetailKeywordsGroupView.as_view(), name='keywords_group_detail'),
    path('add/', AddProjectView.as_view(), name='project_create'),
    path('', ProjectListView.as_view(), name='project_profile'),
    path('<slug:slug>/update/', ChangeProjectView.as_view(), name='project_change'),
    path('<slug:slug>/delete/', DeleteProjectView.as_view(), name='project_delete'),
    path('<slug:slug>/', DetailProjectView.as_view(), name='project_detail'),
    path('search_system/add/<int:project_id>/', AddSearchSystemView.as_view(), name='search_system_create'),
    path('search_system/<int:pk>/', DetailSearchSystemsView.as_view(), name='search_system_detail'),
    path('ajax/get_cities_to_choose/', get_cities_to_choose, name='get_cities_to_choose'),
    path('ajax/create_keywords_group/<int:project_id>/', add_keywords_group, name='create_keywords_group'),
]

project/forms.py
from django import forms

from project.models import (
    Keywords,
    KeywordsGroup,
    Project,
    SearchSystem
)


class AddProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'domain', 'limit_position', 'start_check')


class ChangeProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'domain', 'limit_position', 'start_check')


class AddKeywordsGroupForm(forms.ModelForm):
    name = forms.CharField(
        label='Название группы',
        max_length=255
    )

    class Meta:
        model = KeywordsGroup
        fields = ('name',)


class AddKeywordsForm(forms.ModelForm):
    name = forms.CharField(
        label='Добавить слово',
        widget=forms.widgets.Textarea(),
    )

    class Meta:
        model = Keywords
        fields = ('name', 'keywords_group')

    def __init__(self, *args, **kwargs):
        super(AddKeywordsForm, self).__init__(*args, **kwargs)
        initial = kwargs.get('initial')
        self.fields['keywords_group'].queryset = KeywordsGroup.objects.filter(project_id=initial['project_id'])


class AddSearchSystemForm(forms.ModelForm):
    class Meta:
        model = SearchSystem
        fields = ('name', 'country', 'city', 'language')

templates/keywords/create.html
{% extends "basic.html" %}

{% load bootstrap4 %}

{% block title %}Добавление ключевых слов{% endblock %}

{% block content %}
    <h2>Общая информация</h2>
    <p>Отслеживайте позиции вашего сайта в режиме реального времени</p>

    <form method="post" id="formIdForCreateKeywords"
          action="{% url 'project:keywords_create' project_id=view.kwargs.project_id %}">
        {% csrf_token %}

        <div class="form-group row">
            <label class="col-md-3 col-form-label" for="id_name">Добавить слово:</label>
            <div class="col-md-9">
                <textarea name="addedKeywords" cols="40" rows="7" class="form-control" placeholder="Добавить слово"
                          title
                          required id="id_name"></textarea>
            </div>

        </div>

        <div class="form-group row">
            <label class="col-md-3 col-form-label" for="selectKeywordsGroup">Группа ключевых слов:</label>
            <div class="col-md-9">
                <select name="keywords_group" class="form-control" title required id="idSelectKeywordsGroup">
                    {% for one_keywords_group in form.keywords_group %}
                        {{ one_keywords_group }}
                    {% endfor %}
                    <option value="-1" id="createGroup">Создать группу</option>
                </select>
                <div id="idCreateKeywordGroup" data-url="{{ url }}"></div>
            </div>
        </div>

        <input type="hidden" name="next" value="{{ next }}">
        {% buttons submit='Добавить ключевые слова' %}{% endbuttons %}
    </form>

    <a class="btn btn-primary" href="{% url 'project:search_system_create' project_id=view.kwargs.project_id %}">
        Далее </a>

{% endblock %}