account/urls.py
from django.urls import path

from account.views import (
    IndexView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordChangeView,
    RegisterAccountView,
    RegisterDoneView,
)

app_name = 'account'
urlpatterns = [
    path('password/change/', AccountPasswordChangeView.as_view(), name='password_change'),
    path('register/done', RegisterDoneView.as_view(), name='register_done'),
    path('register/', RegisterAccountView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('', IndexView.as_view(), name='index'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='')),
    path('projects/', include('project.urls', namespace='')),
]

# Запрещаем кэширование на стороне клиента, если сайт функционирует
# в отладочном режиме
# if settings.DEBUG:
#     urlpatterns.append(path('static/<path:path>', never_cache(serve)))

project/urls.py
from django.urls import path

from project.views import (
    add_keywords_group,
    get_cities_to_choose,
    AddKeywordsView,
    AddProjectView,
    AddSearchSystemView,
    ChangeProjectView,
    DetailKeywordsGroupView,
    DetailProjectView,
    DetailSearchSystemsView,
    DeleteProjectView,
    ProjectListView,
    PositionCheckView,
)

app_name = 'project'
urlpatterns = [
    path('all/check/', PositionCheckView.as_view(), name='check_all_positions'),
    path('keywords/add/<int:project_id>/', AddKeywordsView.as_view(), name='keywords_create'),
    path('keywords_group/detail/<int:pk>/', DetailKeywordsGroupView.as_view(), name='keywords_group_detail'),
    path('add/', AddProjectView.as_view(), name='project_create'),
    path('', ProjectListView.as_view(), name='project_profile'),
    path('<slug:slug>/update/', ChangeProjectView.as_view(), name='project_change'),
    path('<slug:slug>/delete/', DeleteProjectView.as_view(), name='project_delete'),
    path('<slug:slug>/', DetailProjectView.as_view(), name='project_detail'),
    path('search_system/add/<int:project_id>/', AddSearchSystemView.as_view(), name='search_system_create'),
    path('search_system/<int:pk>/', DetailSearchSystemsView.as_view(), name='search_system_detail'),
    path('ajax/get_cities_to_choose/', get_cities_to_choose, name='get_cities_to_choose'),
    path('ajax/create_keywords_group/<int:project_id>/', add_keywords_group, name='create_keywords_group'),
]

templates/basic.html
{% load bootstrap4 static project_tags %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Project{% endblock %}</title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/assets/js/jquery-ui-1.12.1.custom/jquery-ui.min.css' %}">

    </head>

    <body class="container-fluid">
        <div class="row">
            <ul class="col nav justify-content-end border">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle mr-5" data-toggle="dropdown"
                        href="#" role="button" aria-haspopup="true"
                        aria-expanded="false">{{ user.email }}</a>
                        <div class="dropdown-menu mr-5">
                            <a class="dropdown-item" href="{% url 'project:project_profile' %}">Все проекты</a>
                            <a class="dropdown-item" href="{% url 'project:project_create' %}">Добавить проект</a>
                            <a class="dropdown-item" href="{% url 'account:password_change' %}">Изменить пароль</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account:logout' %}">Выйти</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Вход</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account:register' %}">
                Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="row">

        </div>

<div class="row">
    <div class="col-2 border">
        {% get_projects request.user %}
    </div>
    <div class="col-8 border">
        {% bootstrap_messages %}
        {% block content %}
        {% endblock %}
    </div>
    <div class="col-2 border">
    </div>
</div>

<div class="row">

</div>
        {% bootstrap_javascript jquery='full' %}
        <script src="{% static '/assets/js/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
        <script type="module" src="{% static '/js/main.js' %}"></script>
</body>
</html>

templates/sidebar.html
<div class="row">
    Проекты:
</div>
<div class="row border">
    <ul>
        {% for my_project in my_projects %}
            <a class="btn btn-info" href="{% url 'project:project_detail' my_project.slug %}">{{ my_project.name }}</a>
        {% empty %}
            <li>нет проектов</li>
        {% endfor %}
    </ul>
</div>
<div class="row border">
    <a class="btn btn-info" target="_blank" href="{% url 'project:check_all_positions' %}">Проверить все позиции</a>
</div>