account/urls.py
from django.urls import path

from account.views import (
    IndexView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordChangeView,
    RegisterAccountView,
    RegisterDoneView,
)

app_name = 'account'
urlpatterns = [
    path('password/change/', AccountPasswordChangeView.as_view(), name='password_change'),
    path('register/done', RegisterDoneView.as_view(), name='register_done'),
    path('register/', RegisterAccountView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('', IndexView.as_view(), name='index'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='')),
    path('projects/', include('project.urls', namespace='')),
]

# Запрещаем кэширование на стороне клиента, если сайт функционирует
# в отладочном режиме
# if settings.DEBUG:
#     urlpatterns.append(path('static/<path:path>', never_cache(serve)))

project/urls.py
from django.urls import path

from project.views import (
    add_keywords_group,
    get_cities_to_choose,
    AddKeywordsView,
    AddProjectView,
    AddSearchSystemView,
    ChangeProjectView,
    DetailKeywordsGroupView,
    DetailProjectView,
    DetailSearchSystemsView,
    DeleteProjectView,
    ProjectListView,
    PositionCheckView,
)

app_name = 'project'
urlpatterns = [
    path('all/check/', PositionCheckView.as_view(), name='check_all_positions'),
    path('keywords/add/<int:project_id>/', AddKeywordsView.as_view(), name='keywords_create'),
    path('keywords_group/detail/<int:pk>/', DetailKeywordsGroupView.as_view(), name='keywords_group_detail'),
    path('add/', AddProjectView.as_view(), name='project_create'),
    path('', ProjectListView.as_view(), name='project_profile'),
    path('<slug:slug>/update/', ChangeProjectView.as_view(), name='project_change'),
    path('<slug:slug>/delete/', DeleteProjectView.as_view(), name='project_delete'),
    path('<slug:slug>/', DetailProjectView.as_view(), name='project_detail'),
    path('search_system/add/<int:project_id>/', AddSearchSystemView.as_view(), name='search_system_create'),
    path('search_system/<int:pk>/', DetailSearchSystemsView.as_view(), name='search_system_detail'),
    path('ajax/get_cities_to_choose/', get_cities_to_choose, name='get_cities_to_choose'),
    path('ajax/create_keywords_group/<int:project_id>/', add_keywords_group, name='create_keywords_group'),
]

project/models.py
from dateutil.relativedelta import relativedelta
from django.db import models
from django.urls import reverse

from account.models import CustomUser


class Project(models.Model):
    LIMIT_HUNDRED = 100
    LIMIT_TWO_HUNDRED = 200

    LIMIT_CHOICES = (
        (LIMIT_HUNDRED, '100'),
        (LIMIT_TWO_HUNDRED, '200'),
    )

    DATE_CHOICES = (
        ('daily', 'Ежедневно'),
        ('every_three_days', 'Раз в 3 дня'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
        ('on_request', 'По запросу'),
    )

    name = models.CharField('Название проекта', max_length=255)

    slug = models.SlugField(max_length=50, unique=True, default="1", verbose_name="Символьный код проекта")

    domain = models.URLField('Адрес сайта', max_length=255)

    limit_position = models.IntegerField(
        'Глубина сбора позиций',
        choices=LIMIT_CHOICES,
        default=LIMIT_HUNDRED,
        help_text='Сервис будет искать сайт включительно до 100-й или 200-й позиции'
    )

    start_check = models.CharField(
        'Периодичность проверок',
        max_length=30,
        choices=DATE_CHOICES,
        default='weekly',
    )

    created = models.DateTimeField('Дата добавления', auto_now_add=True)

    updated = models.DateTimeField('Дата изменения', auto_now=True)

    date_of_check = models.DateTimeField('Дата проверки', blank=True, null=True)

    author = models.ForeignKey(
        CustomUser,
        verbose_name='Автор проекта',
        on_delete=models.CASCADE
    )

    def get_next_check_date(self, date_of_check):
        if self.start_check == 'daily':
            return date_of_check + relativedelta(days=1)

        elif self.start_check == 'every_three_days':
            return date_of_check + relativedelta(days=3)

        elif self.start_check == 'weekly':
            return date_of_check + relativedelta(weeks=1)

        elif self.start_check == 'monthly':
            return date_of_check + relativedelta(month=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        ordering = ('-id',)


class KeywordsGroup(models.Model):
    name = models.CharField('Название группы', max_length=255)

    project = models.ForeignKey(
        Project,
        verbose_name='Проект',
        on_delete=models.CASCADE
    )

    search_systems = models.ManyToManyField(
        'SearchSystem',
        blank=True
    )

    def keyword_group_search_system(self):
        return [search_system for search_system in self.search_systems.all()]

    keyword_group_search_system.short_description = 'Поисковые системы группы ключевых слов'

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('project:keywords_group_detail', kwargs={'pk': self.id})

    class Meta:
        verbose_name = 'Группа ключевых слов'
        verbose_name_plural = 'Группы ключевых слов'


class Keywords(models.Model):
    name = models.TextField('Перечень слов', max_length=255)

    keywords_group = models.ForeignKey(
        KeywordsGroup,
        verbose_name='Группа ключевых слов',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Слово'
        verbose_name_plural = 'Слова'


class SearchSystem(models.Model):
    YANDEX = 'yandex'
    GOOGLE = 'google'
    ENGLISH = 'en'
    RUSSIAN = 'ru'

    LANGUAGE_CHOICES = (
        (ENGLISH, 'english'),
        (RUSSIAN, 'русский'),
    )

    SEARCH_SYSTEM_CHOICES = (
        (YANDEX, 'яндекс'),
        (GOOGLE, 'google'),
    )

    name = models.CharField(
        'Поисковая система',
        max_length=25,
        choices=SEARCH_SYSTEM_CHOICES,
        default=YANDEX
    )

    country = models.CharField('Страна', max_length=50)

    city = models.CharField('Регион', max_length=100)

    geo_id_city = models.IntegerField('Geo id города', )

    language = models.CharField(
        'Язык',
        max_length=25,
        choices=LANGUAGE_CHOICES,
        default=RUSSIAN
    )

    project = models.ForeignKey(
        Project,
        verbose_name='Проект',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.name}, {self.city}'

    class Meta:
        verbose_name = 'Поисковая система'
        verbose_name_plural = 'Поисковые системы'


class RankingsSite(models.Model):
    position = models.PositiveSmallIntegerField('Позиция сайта', )
    project = models.ForeignKey(
        Project,
        verbose_name='Проект',
        on_delete=models.CASCADE
    )
    url_site = models.URLField('Адрес сайта', max_length=255)

    keywords = models.CharField('Ключевые слова', max_length=150)

    keywords_group = models.ForeignKey(
        KeywordsGroup,
        verbose_name='Группы ключевых слов',
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField('Дата добавления', auto_now_add=True)
    updated = models.DateTimeField('Дата изменения', auto_now=True)
    search_system = models.ForeignKey(
        SearchSystem,
        verbose_name='Поисковая система',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        # Продумать в каком виде лучше отображать записи данной модели??
        return f'''
            ПС: {self.search_system},
            фраза: {self.keywords}, 
            URL: {self.url_site}, 
            позиция: {self.position}, 
            дата: {self.updated}   
                '''

    class Meta:
        verbose_name = 'Позиция сайта'
        verbose_name_plural = 'Позиции сайта'

project/forms.py
from django import forms

from project.models import (
    Keywords,
    KeywordsGroup,
    Project,
    SearchSystem
)


class AddProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'domain', 'limit_position', 'start_check')


class ChangeProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'domain', 'limit_position', 'start_check')


class AddKeywordsGroupForm(forms.ModelForm):
    name = forms.CharField(
        label='Название группы',
        max_length=255
    )

    class Meta:
        model = KeywordsGroup
        fields = ('name',)


class AddKeywordsForm(forms.ModelForm):
    name = forms.CharField(
        label='Добавить слово',
        widget=forms.widgets.Textarea(),
    )

    class Meta:
        model = Keywords
        fields = ('name', 'keywords_group')

    def __init__(self, *args, **kwargs):
        super(AddKeywordsForm, self).__init__(*args, **kwargs)
        initial = kwargs.get('initial')
        self.fields['keywords_group'].queryset = KeywordsGroup.objects.filter(project_id=initial['project_id'])


class AddSearchSystemForm(forms.ModelForm):
    class Meta:
        model = SearchSystem
        fields = ('name', 'country', 'city', 'language')

templates/search_system/create.html
{% extends "basic.html" %}

{% load bootstrap4 %}

{% block title %}Поисковые системы{% endblock %}

{% block content %}
    <h2>Общая информация</h2>
    <p>Отслеживайте позиции вашего сайта в режиме реального времени</p>

    <form method="post" id="id_form_search_system"
          action="{% url 'project:search_system_create' project_id=view.kwargs.project_id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Добавить поисковую систему:</label>
            <select name="name" class="form-control" id="id_name">
                <option value="Yandex" selected>Яндекс</option>
                <option value="Google">Google</option>
            </select>
        </div>

        <div class="form-group">
            <label for="id_country">Страна:</label>
            <input type="text" name="country" class="form-control" maxlength="35" id="id_country" placeholder="Страна"
                   required>
        </div>

        <div class="form-group">
            <div class="search-cities-container">
                <label for="id_select_city">Регион</label>
                <input type="text" name="select_city" class="form-control" id="id_select_city" placeholder="Регион"
                       data-url="{{ url }}" required>
                <div class="search-results"></div>
            </div>
        </div>

        <div class="form-group">
            <label for="id_language">Язык:</label>
            <select name="language" class="form-control" id="id_language">
                <option value="en">English</option>
                <option value="ru" selected>Русский</option>
            </select>
        </div>

        <div class="list-group">
            <p class="h3">Поисковые системы добавленные к этому проекту: </p>
            <ol id="searchSystemsContainer">
                {% for search_system in search_systems %}
                    <li> {{ search_system }} </li>
                {% endfor %}
            </ol>
        </div>

        <button type="submit" class="btn btn-success" id="id_button_search_system">Добавить поисковую
            систему
        </button>

        <input type="hidden" name="selected_city_id">

        <input type="hidden" name="next" value="{{ next }}">

    </form>

    <a class="btn btn-primary" href="{% url 'account:index' %}"> Далее </a>

{% endblock %}

templates/search_system/detail.html
{% extends "basic.html" %}

{% load bootstrap4 %}

{% block title %}Информация о проекте{% endblock %}


{% block content %}
    <p><a class="btn btn-primary" href="{% url 'project:project_detail' searchsystem.project.slug %}">Вернуться
        назад</a></p>

    <h5>Группы ключевых слов проекта:</h5>
    {% for keywords_group in keywords_groups %}
        <div>
            <p class="btn btn-info">{{ keywords_group }}:</p>
            {% for keywords in keywords_group.rankingssite_set.all %}
                <ul>
                    <li>{{ keywords }}</li>
                </ul>
            {% endfor %}
            {#  <a class="btn btn-info" href="{{ keywords_group.get_absolute_url }}">{{ keywords_group.name }}</a>  #}
        </div>
    {% endfor %}

{% endblock %}